### PR TITLE
Fix SVG

### LINKED ISSUE #13: Multiple display bugs in v15/v16 icons
Similar to the old case at https://github.com/rugk/streetcomplete-quest-svgs/issues/3 we do have display bugs again. 😢 

Only at Wikimedia, seems their converter to PNG fails again. If you look at the original with Firefox, it still seems to work.

grafik
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_recycling_glass.svg

grafik
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_fee.svg

grafik
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_mail_ref.svg

---

This is annoying and needs a workaround. (may even be the same problem as in the old bug #3)

version: https://github.com/rugk/streetcomplete-quest-svgs/commit/186803d28524249b395ac7e1bae88af3ab22de95

/cc @westnordost

### PR DESCRIPTION
**Pull request by Binnette**

### CODE REVIEW

**Review by rugk — APPROVED** [review]
visual diff confirmed

**Comment by rugk** [comment]
Thanks. :smile:

**Comment by rugk** [comment]
BTW next time: You can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged by adding some "magic" text to your PR _body_. It would be kind, if you could edit your PR to change this.

**Comment by Binnette** [comment]
Thank for sharing me this article :+1: 
Next time, i will do it :wink:

**Pull request merged**
